import { Geist, Geist_Mono, Catamaran } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar/Navbar';

const geistSans = Geist({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800'],
    variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800'],
    variable: '--font-geist-mono',
});

const catamaran = Catamaran({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800'],
    variable: '--font-catamaran',
});

export const metadata = {
    title: 'Store House App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${catamaran.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Navbar />
                {children}
            </body>
        </html>
    );
}
